import { candidatePolicy } from "./policy.mjs";
export function nativeConfig(attempt, endpoint) {
  const policy = candidatePolicy(attempt),
    home = policy.environment.HOME;
  const featuresOff = [
    "goals",
    "apps",
    "plugins",
    "plugin_hooks",
    "hooks",
    "codex_hooks",
    "multi_agent",
    "collab",
    "browser_use",
    "computer_use",
    "in_app_browser",
    "image_generation",
    "js_repl",
    "code_mode",
    "code_mode_host",
    "remote_models",
    "api_key_model_discovery",
    "shell_snapshot",
    "shell_snapshot_v2",
    "shell_zsh_fork",
    "unified_exec_zsh_fork",
    "responses_websockets",
    "responses_websockets_v2",
    "enable_request_compression",
    "web_search",
    "web_search_request",
    "web_search_cached",
    "skill_search",
    "memories",
    "remote_control",
    "system_proxy_fallback",
    "respect_system_proxy",
  ];
  return (
    [
      'model = "gpt-5.4"',
      'model_provider = "synthetic"',
      'approval_policy = "never"',
      'default_permissions = "probe"',
      "allow_login_shell = false",
      "project_doc_max_bytes = 0",
      'web_search = "disabled"',
      'cli_auth_credentials_store = "file"',
      'mcp_oauth_credentials_store = "file"',
      policy.exactPretrust.trimEnd(),
      "[tools.experimental_request_user_input]",
      "enabled = false",
      "[analytics]",
      "enabled = false",
      "[history]",
      'persistence = "none"',
      "[shell_environment_policy]",
      'inherit = "none"',
      "[shell_environment_policy.set]",
      'PATH = "/usr/bin:/bin"',
      `HOME = ${JSON.stringify(home)}`,
      `TMPDIR = ${JSON.stringify(policy.environment.TMPDIR)}`,
      "[features]",
      ...featuresOff.map((f) => `${f} = false`),
      "unified_exec = true",
      "shell_tool = true",
      "skip_host_skill_discovery = true",
      "[model_providers.synthetic]",
      'name = "synthetic-no-inference"',
      `base_url = ${JSON.stringify(endpoint)}`,
      'wire_api = "responses"',
      'env_key = "ROCKY_SYNTHETIC_ONLY_KEY"',
      "requires_openai_auth = false",
      "supports_websockets = false",
      "request_max_retries = 0",
      "stream_max_retries = 0",
      "stream_idle_timeout_ms = 10000",
      ...policy.lines,
    ].join("\n") + "\n"
  );
}
